### ISSUE TITLE
Laser power and power density logged in PLPropertiesLibrary (or PL Settings )

### ISSUE THREAD

**Issue by Pepe-Marquez** [nomad-hzb/nomad-baseclasses#29]
Along with the laser wavelength and the spot size, it would be good to log the laser power, and the power density (derived).

With the power density, and the laser wavelength, on could derive the illuminated photon flux, which is very relevant for this measurements when we want to calculate the PLQY and then derive the implied V_OC. 

To calculate the power density and photon flux from a laser's wavelength, power, and spot size, you can use the following formulas:

Some ChatGPT python code for this:

```python
import math

# Constants
h = 6.626e-34  # Planck's constant in Js
c = 3e8  # Speed of light in m/s

# Function to calculate power density and photon flux
def calculate_laser_parameters(power, wavelength_nm, spot_diameter_mm):
    # Convert wavelength from nm to m and spot diameter from mm to m
    wavelength = wavelength_nm * 1e-9
    spot_diameter = spot_diameter_mm * 1e-3
    
    # Calculate spot area
    radius = spot_diameter / 2
    area = math.pi * (radius ** 2)
    
    # Calculate power density
    power_density = power / area
    
    # Calculate energy of a single photon
    photon_energy = (h * c) / wavelength
    
    # Calculate photon flux
    photon_flux = power / (photon_energy * area)
    
    return power_density, photon_flux

# Example parameters
laser_power = 1  # in W
laser_wavelength_nm = 500  # in nm
laser_spot_diameter_mm = 1  # in mm

# Calculate power density and photon flux
power_density, photon_flux = calculate_laser_parameters(laser_power, laser_wavelength_nm, laser_spot_diameter_mm)

power_density, photon_flux

```

**Comment by RoteKekse** [comment]
the calculation is straight forward, we just need to check with the lab if they can log the laser power in the measurement file, if it is always the same (for now) it would be ok to hard code it as ad default value

**Comment by RoteKekse** [comment]
@Pepe-Marquez this belongs to PL meausrement right?
